
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4  # Use the sha / tag you want to point at
    hooks:
    -   id: pylint
