language: python
python:
  - 3.7
  - 3.6
  - 3.5
services:
  - redis-server
install:
  - pip install pylint
  - pip install flake8
  - pip install -r setup_requirements.txt
  - pip install -r requirements.txt
script:
  - flake8 chariots
  - pylint chariots
  - py.test chariots tests docs --doctest-modules --doctest-glob='*.rst'
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: aredier
  password:
    secure: "WWn4XK19BNz6ijmD2ewj2649FWxhWm4hpPrf8a6jA4akofDiqd5O9vLUdZeIZuR3ohKD9nLqkujOOGOv/aNF3b2rzHm+0vCGeZfbG5bNFmvlUw5MaM9cU4Ja9qGZI3gyYarJWlGD2F///eyWfExPLJSShAZWtihzVUTyYy8IJIIdoyYXYYVwmjxpBe9yjq4IoJCK7Y64hU7XxST209+wElIWQTuESjtIIEIHJjBdtGFGBSVNa/oXyIfYinDfszyLo7hvn7Aj6a4NaFYjCw0HMHhzu0cgxewqT5k3233A5/fWt0iIgmCpE327VmF6zi2SOCztE1lkEmFetIB7cgS0L/XubSEy72+/C5IQ3j66wFkyqs4ysCuXGyZUD7APZcaqd7UBagfNUmfEs2Vc/CJtXsUW1NFZZFgknIc8UxGlYajkzpy8mAtFdw9O91PNswy9TogcsbQ4mqhMs7jBi6FY7ohrXb7yfGvqYypZNQFjqBcf8gli8RQc8GQMA1HO9VRwFOOl6B770WnPgvlM3EGvDksXETrkYcV+Z/rvC6FCGE47Hrvxf3qqInwjjCururEUnSuCaNQhkLvHVtrKAj9pqLylasnaGMZtorO33BbgyL6JLY9GhT9iJ8VUX3o8ZyJBWx0dq/nqlH5Ri6CnSJqlce6gSQnVBUwEf/JZTsZ+MWA="
  on:
    tags: true
    repo: aredier/chariots
    python: 3.5
