language: python
python:
  - 3.7
  - 3.6
  - 3.5
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: aredier
  password:
    secure: "TUfoscqmfa5wxBzLHm8NwUy6L2BvuQOcvNFt29VgbeiODwwT7rFE+JZjma7RpPeA2//Yqm83Wcn/m8ZfU80Abj4JyldHY5LyjQbzL/yEn+1Yo0MgysFBVRQMk/6XGrzfLZTA3voBYIa19Ev8GT6E0LPeEKZQpjTvLoSLWiif2RvYcXmKThYI0O6WvN68B51Ht/plMHOG2piahW1vTTYi8jPKuSmlrdrP77yArZ7y+VI3EEUxkmFMZix5UI9HcL5Oc1UWenfQhE25q6xKh4tdPEVPvE28AuXqyh9J1Xv1gnO083DPMpnClVrrjEfSbtlBP5JdZytZM/kzXHotvy32Kmx3PEcrjJipSLMVDmElArKsCwWr42QQ6yiokImlBryJ8KAxj48csLg0Bn/5VIdJL6ep09rjEgsFloKVh9Bi8UG7Vy6rjELNwIu/E17Tz8Qy4Upueacqvw9AdrbtZB5OBHaBLAfC5fv0RSdnsN4/bi5LQcVIJuCciRhSwA5pN3jWNZpbtTbmX0+7AhijtLR7DrzN1U9mmsOpaLckDYXvdExOodv2FOr6LK+f8nmcWtX13FcqbGL1/LxDNa6WOtd9G0r5mEmmBqUScBTxc28BJ/iodZ6x7ClFlUkfFxScELzC5C5QYecIDAJT/HsEol75ZJ11cSFaTaod0x3/frL7QvU="
  on:
    tags: true
    repo: aredier/chariots
    python: 3.7

